AllCops:
  Include:
    - Rakefile
    - Guardfile
    - Gemfile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - bin/*
    - db/schema.rb
    - config.ru
    - lib/**/*.rake

Rails:
  Enabled: true

# When seeding you want to output information to the console
Rails/Output:
  Exclude:
    - db/seeds.rb

# Commonly used screens these days easily fit more than 80 characters.
Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20
  Exclude:
    - db/migrate/*.rb

Metrics/BlockLength:
  Exclude:
    - db/migrate/*.rb
    - config/environments/*.rb
    - spec/**/*.rb
    - Guardfile
    - config/routes.rb

Metrics/AbcSize:
  Max: 40
  Exclude:
    - db/migrate/*.rb

# Pundit requires inheriting from struct for headless policies
Style/StructInheritance:
  Exclude:
    - app/policies/*.rb

# Use %x() for string-returning command literals. Dislike backticks.
Style/CommandLiteral:
  EnforcedStyle: percent_x

# This seems like clutter and a general maintenance PITA
Style/FrozenStringLiteralComment:
  Enabled: false

# Yeah documentation is nice but leave it alone
Style/Documentation:
  Exclude:
    - db/migrate/*.rb
    - app/serializers/**/*.rb
    - app/controllers/**/*.rb
    - app/decorators/**/*.rb
    - app/policies/**/*.rb

# We do not need to support Ruby 1.9, so this is good to use.
Style/SymbolArray:
  Enabled: true

# Mixing the styles looks just silly.
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

# Most readable form.
Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

# String#% is by far the least verbose and only object oriented variant.
Style/FormatString:
  EnforcedStyle: percent

# { ... } for multi-line blocks is okay, follow Weirichs rule instead:
# https://web.archive.org/web/20140221124509/http://onestepback.org/index.cgi/Tech/Ruby/BraceVsDoEnd.rdoc
Style/BlockDelimiters:
  Enabled: false

# do / end blocks should be used for side effects,
# methods that run a block for side effects and have
# a useful return value are rare, assign the return
# value to a local variable for those cases.
Style/MethodCalledOnDoEndBlock:
  Enabled: true

# THere are times when Rubocop will effectively end up in a loop telling you
# it doesn't like your regexp style. So just disable it
Style/RegexpLiteral:
  Enabled: false

# Enforcing the names of variables? To single letter ones? Just no.
Style/SingleLineBlockParams:
  Enabled: false

# Shadowing outer local variables with block parameters is often useful
# to not reinvent a new name for the same thing, it highlights the relation
# between the outer variable and the parameter. The cases where it's actually
# confusing are rare, and usually bad for other reasons already, for example
# because the method is too long.
Lint/ShadowingOuterLocalVariable:
  Enabled: false

# This is just silly. Calling the argument `other` in all cases makes no sense.
Style/OpMethod:
  Enabled: false

# Mercifully we're living in a world where non-ASCII characters don't clobber
# code, so, let's enjoy that and allow it in our comments. 🎉
Style/AsciiComments:
  Enabled: false
