version: '3'

services:
  app:
    environment:
      RACK_ENV: production
      RAILS_ENV: production
  web:
    ports:
      - 80:80
      - 443:443
    volumes:
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt
