version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.12.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Env prep
          command: |
            mkdir -p /tmp/caches
            apk add --no-cache curl py-pip=9.0.1-r1
            pip install docker-compose==1.18.0
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /tmp/caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /tmp/caches/app.tar | true
      - run:
          name: Build application Docker image
          command: docker build --cache-from=app -t app .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p caches
            docker save -o /tmp/caches/app.tar app
      - save_cache:
          key: v1-{{ .Branch }}
          paths:
            - /tmp/caches/app.tar
      - run:
          name: Run tests
          command: |
            docker-compose -f docker-compose.test.yml up
      - deploy:
          name: Push Docker image
          command: |
            if [ "$CIRCLE_BRANCH" == "production" ]; then
              echo "Deployment started"
            else
              echo "Not deploying branch ${CIRCLE_BRANCH}"
            fi
