development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

staging:
  adapter: postgresql
  encoding: unicode
  database: myflightmap
  host: ubuntu.vm
  username: myflightmap_www
  password: U7wHqvmmJE8AsV
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: myflightmap
  host: localhost
  username: rails_myflightmap_user
  password: Ldp3j4nR
  pool: 5
  timeout: 5000
