default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  port: <%= ENV['DB_PORT_5432_TCP_PORT'] %>
  username: myflightmap
  password: asdqwe123
  pool: 5

development:
  <<: *default
  database: myflightmap_development

test:
  <<: *default
  database: myflightmap_test
